from __future__ import annotations

# https://pl.wikiquote.org/wiki/Przys%C5%82owia_polskie
SENTENCES = [
    "Chłop robotny i baba pyskata zawojują pół świata.",
    "Choćbyś miał złota skrzynie, śmierci się nie wywiniesz.",
    "Choćbyś uciekał przez góry, las – śmierć do ciebie zdąży na czas.",
    "Chodź, chlebie, zjem ciebie.",
    "Chrzest polewaj wodą, wesele – wódką, a pogrzeb – łzami.",
    "Chyba kończy się świat – świnia z pastuchem za pan brat!",
    "Ciemnota – gorsza od zbrodni.",
    "Cieszyć się jak Ruski z roweru.",
    "Co cię nie zabije, to cię wzmocni.",
    "Co jeden polepszy, to drugi popieprzy.",
    "Co jeden rok płaci, to drugi rok traci.",
    "Co jednemu swawola, to drugiemu niewola.",
    "Co komu pisane, to go nie minie.",
    "Co lato odkłada, to zima przejada.",
    "Co łysemu po grzebieniu!?",
    "Co ma piernik do wiatraka?",
    "Co nie siłą, to rozumem.",
    "Co powiesz w sekrecie, to wiedzą w całym powiecie.",
    "Co robisz? Drzwi do lasu.",
    "Co się nie najesz, to się i nie naliżesz.",
    "Co się źle zaczyna, to się dobrze kończy.",
    "Co w czyim sercu na dnie, to wódka wywiedzie snadnie.",
    "Co w kobiecym sercu na dnie, to i diabeł nie odgadnie.",
    "Co za dużo – to niezdrowo.",
    "Co zaszkodziło, to nauczyło.",
    "Co zima przychłodzi, lato wynagrodzi.",
    "Cymbał im puściejszy w środku, tym głośniej dzwoni.",
    "Czapka na uchu, a wesz na brzuchu.",
    "Czego nie można zmienić, to trzeba polubić.",
    "Czego się nauczymy, tego nam nikt nie wydrze.",
    "Czego wiosna nie zasiała – jesień nie urodzi.",
    "Człek zdechnie, a robota zostanie.",
    "Człowiekowi w życiu nie potrzeba więcej: serce do kochania, rozum do myślenia i do pracy ręce.",
    "Czuć się jak ryba w wodzie.",
    "Czyja kosa pierwsza, tego miedza szersza.",
    "Czyj nasiew, tego plon.",
    "Czyja rola, tego wola.",
    "Czy się stoi, czy się leży – jakaś forsa się należy.",
    "Czy to z góry, czy pod górę – furman patrzy w końską dziurę.",
    "Deszcze listopadowe budzą wiatry grudniowe.",
    "Dla chcącego nic trudnego.",
    "Dlatego dwie uszy, jeden język dano, iżby mniej mówiono, a więcej słuchano.",
    "Do ludzi po naukę, do matki po koszulę.",
    "Do Rzymu przez Krym.",
    "Dobra gospodyni dom wesołym czyni.",
    "Dobra jest zupa z bobra, a jeszcze lepsza z wieprza.",
    "Dobre wychowanie – wrócić rano na śniadanie.",
    "Dobry chleb i z ości, jak się kto przepości.",
    "Dobry początek to połowa roboty.",
    "Dobry zwyczaj – nie pożyczaj, jak oddaje, jeszcze łaje.",
    "Dobry zwyczaj – nie pożyczaj, jeszcze lepszy – nie oddawaj.",
    "Drzewa umierają, stojąc.",
    "Drzwi mogą być albo otwarte, albo zamknięte; trzeciej możliwości nie ma.",
    "Dziad, jak odżyje, to cię torbą zabije.",
    "Dzieci i ryby głosu nie mają.",
    "Dzień świętego Alojzego przyczynia wina dobrego.",
    "(My tu) Gadu gadu, (a) chłop śliwki rwie.",
    "Gadać z nim – to jak plewy młócić.",
    "Gadał dziad do obrazu, a obraz doń ani razu.",
    "Gdy Andrzej (30 XI) się zjawi, to i ziemię postawi.",
    "Gdy kota nie ma, myszy harcują.",
    "Gdy kwiecień chmurny, a maj z wiatrami – dobry rok przed nami.",
    "Gdy luty zimny i suchy, sierpień będzie gorący.",
    "Gdy na Wawrzyńca (10 VIII) słota trzyma, do Gromnic (2 II) lekka zima.",
    "Gdy pada w dniu świętej Anny, pada aż do Zuzanny.",
    "Gdy przyjdzie święty Antoni, znać jabłuszko na jabłoni.",
    "Gdy sierpień wrzos rozwija, jesień krótka, szybko mija.",
    "Gdy się człowiek spieszy, to się diabeł cieszy.",
    "Gdy w sierpniu z północy dmucha, zwykle nastaje posucha.",
    "Gdy Zielona Matka [15 VIII] deszcz przynosi, to zwykle na Narodzenie Matki [8 IX] rosi.",
    "Gdy na Gromniczną roztaje, rzadkie będą urodzaje.",
    "Gdy po lipcu gorącym sierpień się ochłodzi, zima twarda i z wielkim śniegiem chodzi.",
    "Gdy pszczoła w kwietniu nieruchliwa – wiosna mokra bywa.",
    "Gdy Trzej Królowie ciepłem darzą, gospodarze o wiośnie gwarzą.",
    "Gdy Wielki Piątek ponury, Wielkanoc bez chmury.",
    "Gdy wrzesień bez deszczów będzie, w zimie wiatru pełno wszędzie.",
    "Gdyby babcia miała drucik, to by była radiem.",
    "Gdyby babcia miała wąsy, to by była dziadkiem.",
    "Gdyby ciocia miała wąsy, byłaby wujaszkiem.",
    "Gdyby kózka nie skakała, to by nóżki nie złamała.",
    "Gdzie cztery nianie, tam dziecko bez nosa.",
    "Gdzie drwa rąbią, tam wióry lecą.",
    "Gdzie dwóch Polaków, tam trzy zdania (opinie).",
    "Gdzie dwóch się bije, tam trzeci korzysta.",
    "Gdzie siła włada – rozumu „nie nada”.",
    "Gdzie Słowianin, tam i pieśni.",
    "Głaszcz chama, to cię kopnie. Kopnij chama, to cię pogłaszcze.",
    "Głupota ludzka nie ma granic.",
    "Gorzkie lekarstwo słodko leczy.",
    "Gość w dom, Bóg w dom.",
    "Grzmot listopada dużo zboża zapowiada.",
    "Hulaj, duszo, pókiś młoda.",
    "I ja waść, i ty waść, a kto będzie świnie paść?",
    "I kwaśne jabłko robak toczy.",
    "Im dalej w las, tym więcej drzew.",
    "Im dąb starszy, tym korzeń twardszy.",
    "Im bucik starszy, tym bardziej nosa zadziera!",
    "Im kto mniej wart, tym wyżej głowę nosi.",
    "Im kto więcej ma, tym więcej chce.",
    "Im mniej wiesz, tym spokojniej śpisz.",
    "Im pies mniej szczeka, tym bardziej gryzie.",
    "Im więcej w grudniu pogody, tym więcej wiosną wody.",
    "Im wyżej siedzisz, z tym większym hukiem zlecisz.",
    "Idzie luty, obuj/podkuj buty.",
    "Jajko mądrzejsze od kury.",
    "Jak baba zechce, to da i przez dziurkę od klucza.",
    "Jak cię widzą, tak cię piszą.",
    "Jak kamień w wodę.",
    "Jak krew w piach.",
    "Jak Kuba Bogu, tak Bóg Kubie.",
    "Jaka marchew, taka nać – taka córka jaka mać, jakie drzewo, taki klin – jaki ojciec, taki syn.",
    "Jak na świętego Antoniego chmurki, to z ziemniakami na górki.",
    "Jak pies je, to nie szczeka, bo mu miska ucieka.",
    "Jak się cenisz, tak cię cenią.",
    "Jak się chce psa uderzyć, kij się znajdzie.",
    "Jak się człowiek śpieszy, to się diabeł cieszy.",
    "Jak się matka z córką zgłosi, tak się koniec grudnia nosi.",
    "Jak się nie ma, co się lubi, to się lubi, co się ma.",
    "Jak się powiedziało „a”, trzeba powiedzieć „b”.",
    "Jak sobie pościelesz, tak się wyśpisz.",
    "Jak spadać, to z dobrego konia.",
    "Jak suka nie da, to pies nie weźmie.",
    "Jak trwoga, to do Boga.",
    "Jak ty komu, tak on tobie.",
    "Jak za króla Sasa. Jedz, pij i popuszczaj pasa.",
    "Jaka matka, taka natka.",
    "Jaka głowa, taka mowa.",
    "Jaka praca, taka płaca.",
    "Jaka ziemia, taka góra, jaka matka, taka córa.",
    "Jakie drzewo, taki klin, jaki ojciec, taki syn.",
    "Jakie jabłko, taka skórka, jaka matka, taka córka.",
    "Jakie pytanie, taka odpowiedź.",
    "Jakie „Szczęść Boże”, takie „Bóg zapłać”.",
    "Jakie życie, taka śmierć.",
    "Jaki pan, taki kram.",
    "Jeden byka doi, drugi sito podstawia!",
    "Jedna jaskółka wiosny nie czyni.",
    "Jednym uchem wchodzi, a drugim wychodzi.",
    "Jesień tego nie zrodzi, czego wiosna nie zasiała.",
    "Jeszcze się taki nie urodził, co by każdemu dogodził.",
    "Jeśli moje zdanie, dobrze mówisz, Janie.",
    "Jeśli wejdziesz miedzy wrony, musisz krakać jak i one.",
    "Kapelusik z piórami, a wszy wyłażą dziurami.",
    "Kapelusz sombrero, a w kieszeni zero.",
    "Kawałek chleba nie spadnie z nieba – pracą na niego zarobić trzeba.",
    "Każda broń palna raz do roku strzela",
    "Każda pliszka swój ogonek chwali.",
    "Każdy jest kowalem swego losu.",
    "Każdy kij ma dwa końce.",
    "Każdy kogut na swych śmieciach śmielszy.",
    "Każdy ma to, na co sobie zasłużył.",
    "Kiedy Pan Bóg zamyka wszystkie drzwi, zawsze zostawia jakieś uchylone okno.",
    "Kiedy styczeń najmroźniejszy, wtedy roczek najpłodniejszy.",
    "Kiedy w styczniu lato, w lecie zima za to.",
    "Kląć jak szewc.",
    "Kłamstwo ma krótkie nogi.",
    "Kochajmy się jak bracia, liczmy się jak Żydzi.",
    "Kochanego ciała nigdy za wiele.",
    "Kochanie gorzej jak więzienie: z więzienia wyzwolą, z kochania nie zdolą.",
    "Kogo nie boli, temu powoli.",
    "Kogo Pan Bóg chce zgubić, temu najpierw rozum odbiera.",
    "Kogo Pan Bóg kocha, temu krzyżyk daje.",
    "Kogut myślał o niedzieli, a w sobotę łeb ucięli.",
    "Kombinuje jak koń pod górę.",
    "Komu w drogę, temu czas.",
    "Koniec języka za przewodnika.",
    "Kowal zawinił, cygana powiesili.",
    "Kruk krukowi oka nie wykole.",
    "Krowa, która dużo ryczy, mało mleka daje.",
    "Krzykiem skrzypiec nie nastroisz.",
    "Kto chleba nie chce, nie wart i kołacza.",
    "Kto daje i odbiera, ten się w piekle poniewiera.",
    "Kto do ciebie z kamieniem – ty do niego z chlebem.",
    "Kto do stołu nakrywa, głodny nie bywa.",
    "Kto gardzi chlebem, nie będzie miał i bułki.",
    "Kto nie ma nic, nie ma nic do stracenia.",
    "Kto nie pracuje ten nie je.",
    "Kto sieje jarke tatarke i proso, to chodzi boso.",
    "Kto nie winien – ten się bać nie powinien, kto nabroił – niech się boi.",
    "Kto nigdy głodu nie czuje, temu i nie smakuje.",
    "Kto ma dużo roli – ten się najada do woli, kto ma mórg niewiele – temu głód przyjacielem.",
    "Kto ma księdza w rodzie, tego bieda nie ubodzie.",
    "Kto ma morgi, krowy, świnie, tego zawsze głód ominie.",
    "Kto ma pobrzękacze, ma i posługacze.",
    "Kto ma pszczoły ten ma miód, kto ma dzieci ten ma smród.",
    "Kto ma złota worek, przed tym wszystkie drzwi otworem.",
    "Kto mieczem wojuje, ten od miecza ginie.",
    "przysłowie wielkopolskie, J. Burszta, Kultura ludowa wielkopolski",
    "Kto nie skropił chleba łzami/potem, nie będzie miał apetytu.",
    "Kto pierwszy, ten lepszy.",
    "Kto po wódce wylewny, u tego sekret niepewny.",
    "Kto pod kim dołki kopie, ten sam w nie wpada.",
    "Kto pyta, ten nie błądzi.",
    "Kto rano wstaje, temu Pan Bóg daje.",
    "Kto rano wstaje, ten jest niewyspany.",
    "Kto sieje wiatr, ten zbiera burze.",
    "Kto się buduje, procesuje i leczy, tego bieda ćwiczy.",
    "Kto się ceni, ten się leni.",
    "Kto się czubi, ten się lubi.",
    "Kto się mądrzejszym czuje, ten głupszemu ustępuje.",
    "Kto się przerzuci z wódki na mleko, nie pociągnie daleko.",
    "Kto skończył siew, może spać do żniw.",
    "Kto wysoko lata, ten nisko siada.",
    "Kto występnym przebacza, ten niewinnych będzie karał.",
    "Kto zakosztuje dobrego, nie patrzy na biedniejszego.",
    "Kto ze sobą nosi, nikogo nie prosi.",
    "Kto ziarno sieje, ten przed burzą zwieje.",
    "Kuj żelazo, póki gorące.",
    "Kwiecień – plecień, co przeplata, trochę zimy, trochę lata.",
    "Kwiecień, gdy deszczem plecie, maj wystroi w kwiecie.",
    "Konia kują, żaba nogę podstawia.",
    "Leje jak z cebra.",
    "Lepiej „być”, niż „mieć”.",
    "Lepiej być pięknym i bogatym, niż brzydkim i biednym.",
    "Lepiej byle jak siedzieć niż dobrze stać.",
    "Lepiej dmuchać na zimne niż się gorącym sparzyć.",
    "Lepiej dać kije stu niewinnym jak puścić płazem jednemu winnemu.",
    "Lepiej dosadzić niż przesadzić.",
    "Lepiej dźwigać jak ścigać.",
    "Lepiej mieć co zdjąć niż nie mieć czego założyć.",
    "Lepiej nie dolać jak przelać.",
    "Lepiej nie dosolić niż przesolić.",
    "Lepiej nie grzeszyć niż do pokuty śpieszyć.",
    "Lepiej nosić niż prosić.",
    "Lepiej późno niż wcale.",
    "Lepiej się ukłonić głowie niż ogonowi.",
    "Lepiej ze swoimi płakać niż z obcymi skakać.",
    "Lepiej zjeść i odchorować niż się miałoby zmarnować.",
    "Lepiej zrozumieć mało niż zrozumieć źle.",
    "Lepiej żałować, że się coś zrobiło, niż żałować, że się nic nie zrobiło.",
    "Lepiej żartować niż chorować.",
    "Lepiej że na głowie niż w głowie łyso.",
    "Lepsza cnota niż wóz złota.",
    "Lepsza jedna panna niż cztery wdowy.",
    "Lepsza u matki polewka niż u obcych marcepany.",
    "Lepsza byle jaka prawda niż dobre kłamstwo.",
    "Lepsze dziś jajko niż jutro kokosza.",
    "Lepsze jedno lato jak dwie zimy.",
    "Lepsze jest wrogiem dobrego.",
    "Lepsze swoje na smole niż czyje w rosole.",
    "Lepszy chleb z solą z dobrą wolą niż marcepan z niewolą.",
    "Lepszy gram handlu niż kilo roboty.",
    "Lepszy mądry wróg niż głupi przyjaciel.",
    "Lepszy na wolności kąsek lada jaki niźli w niewoli przysmaki.",
    "Lepszy rydz niż nic.",
    "Lepszy własny chleb niż pożyczona bułka.",
    "Lepszy wróbel w garści niż gołąb na dachu.",
    "Lepszy wróbel w ręku niż cietrzew na sęku.",
    "Lepszy żywy lis niż martwy lew.",
    "Licho nie śpi.",
    "Ładna buzia to połowa posagu.",
    "Ładnemu we wszystkim ładnie.",
    "Ładny kwiatek krótko przy drodze stoi.",
    "Łagodność uśmierza ból.",
    "Łagodność wszystkiego dokaże.",
    "Łaska pańska na pstrym koniu chadza/jeździ.",
    "Łatwiej brać niż dać.",
    "Łatwiej coś zganić niż zrobić.",
    "Łatwiej kołek obcinkować niż go później pogrubasić.",
    "Łatwiej komu radzić niż dopomóc.",
    "Łatwiej nauczyć się kląć niż czytać.",
    "Łatwiej obiecać niż dotrzymać.",
    "Łatwiej pałac skrytykować niż psu budę postawić.",
    "Łatwiej popsuć niż naprawić.",
    "Łatwiej słuchać niż rozkazywać.",
    "Łatwiej sto pcheł upilnować niż jednej dziewczyny.",
    "Łatwiej wojnę zacząć niż ją skończyć.",
    "Łatwiej z góry jak pod górę.",
    "Łatwiej zranić niż leczyć.",
    "Łatwo być hojnym z cudzego.",
    "Łatwo cudzym szafować.",
    "Łatwo przyszło – łatwo poszło.",
    "Łut szczęścia lepszy, niż cetnar rozumu.",
    "Łyżka dziegciu beczkę miodu zepsuje.",
    "Ma coś z rycerza – zakuty łeb.",
    "Maj z grzmotami – rok dobry przed nami.",
    "Małe dzieci – mały kłopot, duże dzieci – duży kłopot.",
    "Masz babo placek.",
    "Mądra matka dba o swe córki.",
    "Mądrej głowie dość dwie słowie.",
    "Mądrej głowy włos się nie trzyma.",
    "Mądry głupiemu zawsze ustępuje.",
    "Mądry Polak po szkodzie.",
    "Miłe złego początki.",
    "Mnich tak odpowiada, jak mu opat śpiewa.",
    "Modli się pod figurą, a diabła ma za skórą.",
    "Mokry deszczu się nie boi!",
    "Mowa jest srebrem, a milczenie złotem.",
    "Mówił dziad do obrazu, a ten do niego ani razu.",
    "Mieć dwie lewe ręce.",
    "Miłość od pierwszego wejrzenia.",
    "Mój dom jest moją twierdzą.",
    "Muru głową nie przebije, a morza nikt nie wypije.",
    "Myślał indyk o niedzieli, a w sobotę łeb mu ścieli.",
    "Na Agnieszkę mróz, składaj chłopie wóz.",
    "Na Alberta sianokosów pełna sterta.",
    "Nawet dobre pióro kleksy robi.",
    "Na Andrzeja mróz, gotuj na zimę wóz, a jak taje, to znów sanie.",
    "Na Gromniczną mróz – ładuj chłopie wóz, na Gromniczną ciecze – to się zima wlecze.",
    "Na Nowy Rok pogoda – będzie w polu uroda, na Nowy Rok pluta – będzie w polu pokuta.",
    "„Na oko” – to chłop w szpitalu leżał.",
    "Na pieniądzach świat nie stoi.",
    "Na to daje gębie papać, by umiała dobrze kłapać.",
    "Na świętego Albina rzadka u ludzi mina, bo post się zaczyna.",
    "Na święty Ambroży poprawią się mrozy.",
    "Na święty Antoni pierwsza się jagódka zapłoni.",
    "Na święty Walenty uciekają z domu centy.",
    "Nadgorliwość gorsza od faszyzmu.",
    "Nadzieja umiera ostatnia.",
    "Najgorzej, jak komu woda sodowa uderzy do głowy.",
    "Najlepsze mienie – czyste sumienie.",
    "Najpierw klęczy, prosi, szlocha, potem krzyczy: dość, wynocha!",
    "Natura ciągnie wilka do lasu.",
    "Nauka nie poszła w las.",
    "Nawet mistrzowi nie zaszkodzi nauka.",
    "Ni brat, ni swat.",
    "Na stary picy młody ogier sie ćwicy.",
    "Ni do rady, ni do zwady.",
    "Ni do szabli, ni do kądzieli.",
    "Ni prośbą, ni groźbą.",
    "Ni przypiął, ni przyłatał.",
    "Ni przypiął, ni wypiął.",
    "Ni to pies, ni zając.",
    "Ni w Boga wierzy, ni się diabła boi.",
    "Ni widu, ni słychu.",
    "Ni w pięć, ni w dziewięć.",
    "Ni zdolności, ni ochoty.",
    "Nic mu nie będzie, bo głupi.",
    "Nic tak dobrze nie przenika jak gorzałka do przełyka.",
    "Nie bądź w gorącej wodzie kąpany.",
    "Nie budź licha, kiedy śpi.",
    "Nie chce góra przyjść do Mahometa, musi Mahomet przyjść do góry.",
    "Nie czas żałować róż, gdy płoną lasy.",
    "Nie człowiek życie wymyślił, ale takim je zastał.",
    "Nie czyń bliźniemu, co tobie niemiłe.",
    "Nie dasz chłopakom, to dasz robakom.",
    "Nie pomoże ranne wstanie i pomału obracanie",
    "Nie dla pieniędzy się żyje, lecz za nie.",
    "Nie dolewaj oliwy do ognia.",
    "Nie dziel skóry na niedźwiedziu.",
    "Nie głaskaj kota pod włos.",
    "Nie idź spać w gniewie, bo czy się obudzisz – nie wiesz.",
    "Nie ilość – lecz jakość.",
    "Nie każda głowa siwa mądra bywa.",
    "Nie kąsa się ręki, która karmi.",
    "Nie kijem go, to pałą.",
    "Nie kładź palca między drzwi.",
    "Nie kracz, nie kracz, bo wykraczesz.",
    "Nie ma głupich pytań, są tylko głupie odpowiedzi.",
    "Nie masz cwaniaka nad Warszawiaka.",
    "Nie ma tego złego, co by na dobre nie wyszło.",
    "Nie ma reguły bez wyjątku.",
    "Nie ma to jak we własnym domu.",
    "Nie masz na upór lekarstwa.",
    "Nie miała baba kłopotu, kupiła sobie prosię.",
    "Niemiła księdzu ofiara, chodź, cielę, do domu.",
    "Nie można dwom panom służyć.",
    "Nie mów, co myślisz – myśl, co mówisz.",
    "Nie mów hop, póki nie przeskoczysz.",
    "Nie mów nikomu, co się dzieje w domu.",
    "Nie mów nikomu, co tobie niemiłe.",
    "Nie na to żyjemy, byśmy jedli i pili, lecz na to pijem i jemy, abyśmy żyli.",
    "Nie nos dla tabakiery, lecz tabakiera dla nosa.",
    "Nie odkładaj na jutro tego, co masz zrobić dziś.",
    "Nie pluj w studnię, bo może ci przyjść kiedyś czerpać z niej wodę.",
    "Nie po to głowa, by na niej czapkę nosić.",
    "Nie pożyczaj, zły obyczaj.",
    "Nie pożyczywszy – na tydzień gniewu, pożyczywszy – na cały rok.",
    "Nie pomoże mydło, ani malowidło, ani studnia wody, jak nie ma urody.",
    "Nie pomoże uczoność, ani nieskończoność, ani fura sprzętu, jak nie ma talentu.",
    "Nie przebieraj panno, żebyś nie przebrała, żebyś za kanarka wróbla nie dostała.",
    "Nie przesadza się starych drzew.",
    "Nie rozdzielaj włosa (zapałki) na czworo.",
    "Nie rzucaj pereł między wieprze.",
    "Nie rzucaj słów na wiatr.",
    "Pismo Święte Starego i Nowego Testamentu, Pallotinum, Poznań 2003, Mt 4, 4 Łk 4, 4",
    "Nie śmiej się, dziadku, z czyjegoś wypadku – dziadek się śmiał i to samo miał.",
    "Nie taki diabeł straszny, jak go malują.",
    "Nie ten święty, co zgięty.",
    "Nie to ładne, co piękne, ale co się komu podoba.",
    "Nie ucz matki jak się dzieci robi.",
    "Nie warto płakać nad rozlanym mlekiem.",
    "Nie wchodzi się dwa razy do tej samej rzeki.",
    "Nie wie głowa, co język bełkocze.",
    "Nie wierz nigdy dziewucho, coć chłop szepce na ucho.",
    "Nie wierz nigdy mężczyźnie, to słodki cukierek maczany w truciźnie.",
    "Nie wsadzaj nosa do cudzego prosa.",
    "Nie wszystko da się kupić za pieniądze.",
    "Nie wszystko się godzi, co wolno.",
    "Nie wścibiaj nosa, gdzieś nie dał grosza.",
    "Nie wtykaj kija w mrowisko.",
    "Nie wtykaj nosa w nie swoje sprawy.",
    "Nie wychylaj nosa, to ci go nie przytrą.",
    "Nie wykręcaj kota ogonem.",
    "Nie zabija się kury znoszącej złote jajka.",
    "Nie z jednego pieca jadł chleb.",
    "Nie zmienia się koni podczas przeprawy przez rzekę.",
    "Nie życz złego nikomu, byś tego nie zastał w domu.",
    "Niech ci Pan Bóg w dzieciach wynagrodzi.",
    "Niech to będzie kłak, czy wełna – byle była kiszka pełna.",
    "Niejeden rekin sobie życzy, by dorodna szprotka wiodła go na smyczy.",
    "Nigdy nie jest tak źle, żeby nie mogło być gorzej, ani tak dobrze, żeby nie mogło być lepiej.",
    "Nigdy nie należy palić za sobą wszystkich mostów.",
    "Nigdy nie pluj pod wiatr.",
    "Nikt nie jest dobrym sędzią w swojej własnej sprawie.",
    "Nikt nie jest prorokiem między swymi.",
    "Nikt nie odgadnie, co u kogo w sercu na dnie.",
    "Nikt się mądrym nie rodzi, ale staje.",
    "Nim się baba uszpili, chłop przejdzie pół mili.",
    "Nosić drzewo do lasu.",
    "Nosi go jak Żyda po pustym sklepie.",
    "Nowa miotła lepiej zamiata.",
    "Nowego kłamstwa słucha się chętniej, niż starej prawdy.",
    "Nudne jak flaki z olejem.",
    "Nudy na pudy.",
    "O pieniądzach się nie mówi, pieniądze się ma.",
    "Obijać się jak Żyd po pustym sklepie.",
    "Od piwa głowa się kiwa.",
    "Od wódki rozum krótki.",
    "Od przybytku głowa nie boli.",
    "Od Sasa do Lasa.",
    "Ogień i woda, dobrzy słudzy, lecz źli gospodarze.",
    "Od świętej Anki zimne wieczory, chłodne poranki.",
    "Oliwa sprawiedliwa, zawsze na wierzch wypływa.",
    "Palec skaleczysz – cała ręka boli.",
    "Paluszek i główka to szkolna wymówka.",
    "Papier jest cierpliwy: wszystko przyjmie.",
    "Pasuje jak piąte koło u wozu.",
    "Pasuje jak pięść do nosa.",
    "Pasuje jak garbaty do ściany.",
    "Pasuje jak kwiatek do kożucha.",
    "Pasuje jak wilk do pilnowania owiec.",
    "Pasuje jak świni siodło.",
    "Pasuje jak wół do karety.",
    "Patrzy jak cielę na malowane wrota.",
    "Patrzy jak sroka w gnat.",
    "Październik ciepły, będzie luty strzepły.",
    "Póki życia, póty nauki.",
    "Póty dzban wodę nosi, póki się ucho nie urwie.",
    "Pan każe – sługa musi.",
    "Pańskie oko konia tuczy.",
    "Pan Bóg nie rychliwy, ale sprawiedliwy.",
    "Pan Bóg stworzył byka – i byk był; a chłop wziął kozika, urżnął mu u dołu i stworzył wołu.",
    "Pieniądze szczęścia nie dają.",
    "Pierwej rozważ, potem odważ.",
    "Pierwsze koty za płoty.",
    "Pierwsze pół życia żyjemy marzeniami, a drugie pół – wspomnieniami.",
    "Pierwsze śliwki – robaczywki.",
    "Pies ogrodnika; samemu nie zje i drugiemu nie da.",
    "Pijak podobny jest do zwierza: ni do roboty, ni do pacierza.",
    "Plotka wyleci wróblem, a powróci wołem.",
    "Po burzy zawsze słońce przychodzi.",
    "Po karnawale – czas na gorzkie żale.",
    "Po każdej nocy wschodzi słońce.",
    "Po świętej Agacie wyschną na słońcu gacie.",
    "Pod latarnią najciemniej.",
    "Podłość ludzka nie ma granic.",
    "Podobni jak dzień do nocy.",
    "Podróże kształcą.",
    "Poeta... tylko głowa nie ta.",
    "Pokorne cielę dwie matki ssie.",
    "Polak, Węgier dwa bratanki – i do szabli, i do szklanki.",
    "Polska cnota: każdemu otworzyć wrota.",
    "Porywać się z motyką na słońce.",
    "Postać anielska, dusza diabelska.",
    "Pośpiech jest wskazany tylko przy łapaniu pcheł.",
    "Pośpiech jest złym doradcą.",
    "Potrzebne jak dziura w moście.",
    "Potrzebne jak zającowi dzwonek na polowaniu.",
    "Po winie rozum w głowie ginie.",
    "Poznać łatwo w starości, jaki kto był w młodości.",
    "Poznać pana po cholewach.",
    "Poznać po mowie, co kto ma w głowie.",
    "Poznasz głupiego po śmiechu jego.",
    "Pozory często mylą.",
    "Praca nie zając, nie ucieknie.",
    "Pracuj, a garb ci sam wyrośnie.",
    "Prawa są równie jako pajęczyna: wróbel się przeciśnie, a na muszkę wina.",
    "Prawda i cnota ginie od złota.",
    "Prawda jak oliwa – zawsze na wierzch wypływa.",
    "Prawda w oczy kole.",
    "Prawda zawsze zwycięża.",
    "Prawdziwa wiedza to znajomość przyczyn.",
    "Prawdziwego przyjaciela poznaje się w biedzie.",
    "Prawem i lewem.",
    "Proste drzewo nie rzuca garbatego cienia.",
    "Prosty czy krzywy – każdy chce być szczęśliwy.",
    "„Proszę”, „przepraszam”, „dziękuję” – pomaga, a nic nie kosztuje.",
    "Przed zającem żaby uciekają.",
    "Przepadło jak kamień w wodę.",
    "Przepisy są po to, aby je łamać.",
    "Przezorny – zawsze ubezpieczony.",
    "Przyganiał kocioł garnkowi, a sam smoli.",
    "Przyjaciela szukaj blisko, wroga daleko.",
    "Przyjaźń zawarta przy kieliszku wódki zwykle ma żywot krótki.",
    "Przyszła koza do woza.",
    "Przyszła kryska na Matyska.",
    "Pycha i z nieba spycha.",
    "Rób a rób, zarobisz na grób.",
    "Raz na ruski rok.",
    "Ranne wstawanie i wczesna żeniaczka jeszcze nikomu nie zaszkodziły.",
    "Raz na wozie, raz pod wozem.",
    "Ręka rękę myje.",
    "Reguła prosta, że aż osłupia: kto się wymądrza, ten się wygłupia.",
    "Sam jak palec.",
    "Sam sobie powiedział i sam się uśmiał.",
    "Sam sobie sterem, żeglarzem, okrętem.",
    "Samotnemu cały świat pustynią.",
    "Samotny jak kołek w płocie.",
    "Sen mara – Bóg wiara.",
    "Siła złego na jednego.",
    "Siedzieć cicho jak mysz pod miotłą.",
    "Siejesz wiatr – zbierasz burze.",
    "Skąpy (chytry) dwa razy traci.",
    "Skleroza nie choroba tylko nogi bolą.",
    "Skoro jest tak dobrze, to dlaczego jest tak źle?",
    "Słodkie życie – jak w Madrycie.",
    "Słońce i woda zawsze zdrowia doda.",
    "Słońcu i miłości nigdy się w oczy nie patrzy.",
    "Słowo się rzekło, kobyłka u płota.",
    "Słówko wyleci wróblem, a powróci wołem.",
    "Służ panu wiernie, on ci za to pierdnie.",
    "Słuchaj uchem, a nie brzuchem.",
    "Sport to zdrowie.",
    "Sposób na zdrowie człeka – od lekarzy z daleka.",
    "Sprawiedliwość bez dobroci okrucieństwem jest.",
    "Sprzedać się za miskę soczewicy.",
    "Stara miłość nie rdzewieje.",
    "Stare buty najwygodniejsze.",
    "Starego psa nie nauczysz aportować.",
    "Starego wróbla na plewy nie złapiesz.",
    "Stare psisko dobre, jak leży pod płotem.",
    "Stare to są dobre: fortepian i skrzypce.",
    "Stare wino, żona młoda, niejednemu życia doda.",
    "Starość nie radość, młodość nie wieczność.",
    "Starość nie radość, śmierć nie wesele.",
    "Stary, a głupi.",
    "Stary, ale jary.",
    "Stoi jak wół na granicy.",
    "Strach ma wielkie oczy.",
    "Strachy na Lachy.",
    "Stroić się w cudze piórka.",
    "Strzeżonego Pan Bóg strzeże.",
    "Strzeż się psa milczącego i spokojnej wody.",
    "Styczeń pogodny wróży rok płodny.",
    "Suchy marzec, mokry kwiecień i maj chłodny – wróżą rok niegłodny.",
    "Suchy marzec, mokry maj, będzie żytko niby gaj.",
    "Swoje brudy trzeba prać w domu.",
    "Swojego nie puszczaj, po cudze nie sięgaj.",
    "Syty głodnego nie zrozumie.",
    "Szaleć jak pies spuszczony z łańcucha.",
    "Szczenięcej miłości wątek – pieskiego życia początek.",
    "Szczęściarzowi nawet wół się ocieli.",
    "Szczęście człowieka psuje, nieszczęście hartuje.",
    "Szczęście czego mi nie dało, tego mi nie będzie brało.",
    "Szczęście dziś matką, a jutro może być macochą.",
    "Szczęście głupim sprzyja.",
    "Szczęście gdy trafi na głupiego, wszystkim go czyni nieznośnego.",
    "Szczęśliwi czasu nie liczą.",
    "Szewc bez butów chodzi.",
    "Szlachcic na zagrodzie równy wojewodzie.",
    "Szlachetne zdrowie, nikt się nie dowie jako smakujesz – aż się popsujesz.",
    "Szukajcie, a znajdziecie.",
    "Szukać igły w stogu siana.",
    "Szybka decyzja to połowa zwycięstwa.",
    "Ściany mają uszy.",
    "Ślepy afekt i pamięć z człowieka wywlecze.",
    "Ślusarz zawinił, a kowala powiesili.",
    "Śmiałby się człowiek dookoła głowy żeby nie uszy.",
    "Śmiech to zdrowie.",
    "Śmieje się jak głupi do sera.",
    "Śmierć i żona od Boga przeznaczona.",
    "Śniadanie zjedz sam, obiadem podziel się z przyjacielem, a kolację daj wrogowi.",
    "Śpiesz się powoli.",
    "Świat i kalesony",
    "Święta Agnieszka wypuszcza skowronka z mieszka.",
    "Święta, Święta i... po Świętach.",
    "Święty Alojzy miód w plastrach dojrzy.",
    "Święty Antoni o gryce siać przypomni.",
    "Święty Antoni od zguby broni.",
    "Święty Antoni złodziei goni.",
    "Świnia się nie myje – i żyje.",
    "Tanie mięso psy jedzą.",
    "Tanie kupisz, psom wyrzucisz.",
    "Temu czapkują, przy kim pieniądz czują.",
    "Ten się nie myli, kto nic nie robi.",
    "Tłumaczyć z polskiego na nasze.",
    "Trafić z deszczu pod rynnę.",
    "Trud człowieczy czas niweczy.",
    "Trunek mocny, białogłowa grzeszna – z najmędrszego uczynią błazna.",
    "Trzej najlepsi lekarze: dr Spokój, dr Dieta i dr Humor.",
    "Tu goli – i tam strzyże.",
    "Tu leży pies pogrzebany.",
    "Tylko głupiec dyskutuje z końskim zadem.",
    "Tylko krowa zdania nie zmienia.",
    "Tylko trzewik wie, że pończocha dziurawa.",
    "Ucz się, ucz, bo nauka to do potęgi klucz.",
    "Umarłego płaczem nie wskrzesi.",
    "Umiesz liczyć, licz na siebie.",
    "W lipcu upały, w grudniu mróz ostry i stały.",
    "W listopadzie ziemia ciepła, zima będzie skrzepła.",
    "W święty August koniec burz.",
    "Za babą i diabeł nie trafi.",
    "Za dukata brat sprzeda brata.",
    "Zawodu szewca trzeba się wyuczyć, a do wyższych stanowisk wystarczy sukienka duchowna.",
    "Zbój zbója pogoni.",
    "Źle się w marcu urodzić, bo trudno takiemu dogodzić.",
    "Żebro Adamowe nie przynosi tak wiele pożytku jak szkody.",
    "Żeby ciocia miała wąsy, toby była wujkiem.",
    "Żeby dać, trzeba mać.",
    "Żeby kózka nie skakała, to by nóżki nie złamała.",
    "Żeby nie ten „dech”, toby człowiek zdechł.",
    "Agnieszka łaskawa puszcza skowronka z rękawa.",
    "Bartłomieja cały wrzesień naśladuje, i z nim jesień.",
    "Bartłomieja świętego dzień w jakiej zostaje porze, taką jesień bez ochyby daje.",
    "Deszcz św. Jana obiecuje mokre żniwa.",
    "Deszcz w św. Floriana, skrzynia groszem napchana.",
    "Gdy na św. Bernarda ziemia twarda, zima będzie harda.",
    "Gdy przyjdzie św. Agnieszka, przebije lód ogonem pliszka.",
    "Gdy się deszcz w święto Jana opuści obfity, po nim w kilka dni, wierz mi, bywa pozbyty.",
    "Gdy w dzień Adama i Ewy mróz i pięknie, zima wcześnie pęknie.",
    "Gdy w św. Barbarę ostre mrozy, to na zimę gotuj wozy; a gdy roztajanie, każ opatrzyć sanie.",
    "Jak na św. Agnieszkę mróz, to wygryzki do nawozu włóż.",
    "Jak w świętą Annę deszcz pada, to robak orzechy zjada.",
    "Jaki Bartek, taki wrzesień, jaki Marcin, taka zima.",
    "Jeśli na Agnieszkę pochmurno, to o len nie trudno; a jeśli jasno, to o len ciasno.",
    "Jeśli święta Agnieszka wypuści skowronka z mieszka, to już zima na ziemi długo nie pomieszka.",
    "Jeżeli w dzień św. Jacka deszcz nie pada, będzie jesień sucha.",
    "Kiedy na św. Barbarę błoto, będzie zima jak złoto.",
    "Na dzień św. Doroty ma być śniega nad płoty.",
    "Na Kazimiera zima umiera.",
    "Na św. Agatę wysuszysz na słońcu szmatę.",
    "Na św. Agnieszkę, wychodzi woda na ścieżkę.",
    "Na św. Ambroży poprawiają się mrozy.",
    "Na św. Annę mrowiska, szukaj w zimie ogniska.",
    "Na św. Barbarę, jeżeli mróz i pogoda, zima będzie lekka i bez śniegu.",
    "Na św. Bartłomieja mroźnej zimy jest nadzieja.",
    "Na św. Franciszka zielenią się łany i ze swego zimowiska wracają bociany.",
    "Od świętej Anki zimne wieczory i ranki.",
    "Od św. Anki zimne poranki.",
    "Od św. Anny nie doczeka południa deszcz poranny.",
    "Po św. Agacie wyschnie bielizna na płocie.",
    "Po św. Agnieszce napije się wół na ścieżce.",
    "Po św. Ewie chodzi się w cholewie.",
    "Po św. Bartłomieju z łyżki deszczu ceber błota.",
    "Serwacy, Pankracy, Bonifacy – zły na ogród chłopacy.",
    "Susza w św. Bartłomieja, mroźnej zimy jest nadzieja.",
    "Św. Barbara chłopa utopi, albo umrozi.",
    "Św. Barbara po lodzie, Boże Narodzenie po wodzie.",
    "Św. Hanna, to już jesienna panna.",
    "Św. Agnieszki, pół zimy końskiej.",
    "Św. Bartłomiej pogodny, jesień pogodna.",
    "Św. Zofija kłosy rozwija.",
    "W dzień św. Agaty, jeśli słonko przez okienko zajrzy do chaty, to wiosenka na świat poogląda zza zimowej kraty.",
    "Baba śląska: w barach szeroka, w dupie wąska.",
    "Brudny jakby się z gównem bił.",
    "Choćby skały srały.",
    "Ciemno jak w dupie u Murzyna.",
    "Czy kłak czy wełna – byle dupa pełna.",
    "Głowa niemiecka a dupa radziecka.",
    "Gówno lepiej obejść, jak ruszyć.",
    "Jak nie urok, to sraczka.",
    "Jak się nie odwrócić – zawsze dupa z tyłu.",
    "Każde gówno źle pachnie.",
    "Mów do słupa, a słup dupa.",
    "Mów do dupy to cię osra.",
    "Myśleć jak z gówna skórkę ściągnąć.",
    "Na św. Bartłomiej z dupą pod płomień!",
    "Nie ma większego gałgana jak z gnoja wyjdzie na pana.",
    "Nie rozrabiaj, nie podskakuj, siedź na dupie i przytakuj.",
    "Nie widziała dupa słońca, zagorzała od miesiąca.",
    "Pasuje jak kij do dupy.",
    "Po co jesz? I tak gówno z tego masz.",
    "Samotny jak palec w dupie.",
    "Śpiewa jakby mu sierp z dupy ciągnął.",
    "Srała, grała, dupy nie widziała.",
    "Swoje – do kupki, czyje – do dupki.",
    "Szkoda, to jest jak krowa do studni nasra: ani wody ani gówna nie ma.",
    "Taki z niego muzykant jak z koziego ogona klarnet, a z koziej dupy trąba.",
    "To nie sztuka zabić kruka, ale gołą dupą jeża.",
    "Własne gówno nie śmierdzi.",
    "Wódka i dupka zrobią z chłopa trupka.",
    "Wyżej dupy nie przeskoczysz (podskoczysz).",
]
